name: TrMenu Dev

on:
  push:
    branches: [ stable/v3 ]

jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload TrMenu
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "TrMenu"
          automatic_release_tag: "trmenu"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/*.jar"
          prerelease: true