name: TrMenu Dev

on:
  push:
    branches: [ stable/v3 ]
  pull_request:
    branches: [ stable/v3 ]

jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

        # output jar
      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: TrMenu Dev
          path: build/libs/*.jar